### ISSUE TITLE
test: Unit tests for wallet modules

### ISSUE THREAD

**Issue by rajarshimaitra** [utxo-teleport/teleport-transactions#20]
Wallet modules majorly lacks various unit tests. Cover each module with it's module-specific unit tests.

**Comment by Shourya742** [comment]
@rajarshimaitra I am considering proceeding with the wallet test since there are still a substantial number of modules yet to be covered. Whats ur thought?

<img width="1310" alt="Screenshot 2023-11-20 at 10 27 53 PM" src="https://github.com/utxo-teleport/teleport-transactions/assets/84662239/1531fa68-5ecf-4616-aa60-5abc4688d57b">

**Comment by rajarshimaitra** [comment]
Sounds good. Yes the Wallet functions are crucial to test. And I think this will get us to >80% test coverage milestone. Most other modules are covered. 

In terms of priority, I would suggest:
- swapcoins
- funding
- api
- direct send (remaining)
- Fidelity (this module needs clean up, so can be done after I am done with the code).

**Comment by rajarshimaitra** [comment]
We have individual issues for them. Closing.
